### ISSUE TITLE
Purpose of hash table `id_var_map` in algorithm w infer instantiate function

### ISSUE THREAD

**Issue by lpil** [tomprimozic/type-systems#10]
A question, possibly stemming from a misunderstanding on my part

In this function a hash table is created.

https://github.com/tomprimozic/type-systems/blob/7c4f5d3ea775c5fdd7c51ea7b84f08f2fea7865a/algorithm_w/infer.ml#L87

It is used in the `TVar {contents = Generic id}` branch, where the table is updated with a var if it does not already contain it.

https://github.com/tomprimozic/type-systems/blob/7c4f5d3ea775c5fdd7c51ea7b84f08f2fea7865a/algorithm_w/infer.ml#L92-L97

If I'm not misreading, the recursive function terminates immediately after the new var is added to the hashtable, causing the table to go out of scope and be deallocated.

With this in mind it seems like the hashtable is never used and could be removed. Is this correct?

**Comment by tomprimozic** [comment]
The `id_var_map` hashtable is shared between different invocations of the recursive helper function `f`, so that the same `Generic` `TVar` (i.e. the one with the same `id`) results in the same `Unbound` `TVar`.

The idea is that if we're instantiating a function like `id` with type `forall[a] a -> a`, both instances of `a` in argument and result positions of `->` are assigned the same unbound variable, so the resulting type for type inference is `_x -> _x`, not `_x -> _y`.

Does this explain the code?

**Comment by lpil** [comment]
Oh I see! OCaml's mutable data structures are tricking my immutable Erlang mind.

Thank you very much for the clarification and for these examples in general :)
